{"time":"2025-03-17T21:24:30.2608569+05:30","level":"INFO","msg":"stream: starting","core version":"0.19.8","symlink path":"C:\\Users\\praha\\Documents\\IIT madras\\Acads\\sem 10\\introtoDL\\DA6401_A01\\wandb\\run-20250317_212430-rnpt4htx\\logs\\debug-core.log"}
{"time":"2025-03-17T21:24:30.3787474+05:30","level":"INFO","msg":"created new stream","id":"rnpt4htx"}
{"time":"2025-03-17T21:24:30.3787474+05:30","level":"INFO","msg":"stream: started","id":"rnpt4htx"}
{"time":"2025-03-17T21:24:30.3787474+05:30","level":"INFO","msg":"writer: Do: started","stream_id":"rnpt4htx"}
{"time":"2025-03-17T21:24:30.3787474+05:30","level":"INFO","msg":"sender: started","stream_id":"rnpt4htx"}
{"time":"2025-03-17T21:24:30.3792576+05:30","level":"INFO","msg":"handler: started","stream_id":"rnpt4htx"}
{"time":"2025-03-17T21:24:51.4320092+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T21:24:53.8842356+05:30","level":"ERROR","msg":"HTTP error","status":401,"method":"POST","url":"https://api.wandb.ai/graphql"}
{"time":"2025-03-17T21:24:53.8851191+05:30","level":"ERROR","msg":"sender: upsertRun:","error":"failed to upsert bucket: returned error 401: {\"data\":{\"upsertBucket\":null},\"errors\":[{\"message\":\"user is not logged in\",\"path\":[\"upsertBucket\"],\"extensions\":{\"code\":\"PERMISSION_ERROR\"}}]}"}
