{"time":"2025-03-17T22:51:00.6276132+05:30","level":"INFO","msg":"stream: starting","core version":"0.19.8","symlink path":"C:\\Users\\praha\\Documents\\IIT madras\\Acads\\sem 10\\introtoDL\\DA6401_A01\\wandb\\run-20250317_225100-6znlqhpb\\logs\\debug-core.log"}
{"time":"2025-03-17T22:51:00.7422369+05:30","level":"INFO","msg":"created new stream","id":"6znlqhpb"}
{"time":"2025-03-17T22:51:00.7422369+05:30","level":"INFO","msg":"stream: started","id":"6znlqhpb"}
{"time":"2025-03-17T22:51:00.7427417+05:30","level":"INFO","msg":"sender: started","stream_id":"6znlqhpb"}
{"time":"2025-03-17T22:51:00.7427417+05:30","level":"INFO","msg":"writer: Do: started","stream_id":"6znlqhpb"}
{"time":"2025-03-17T22:51:00.7428197+05:30","level":"INFO","msg":"handler: started","stream_id":"6znlqhpb"}
{"time":"2025-03-17T22:51:01.1630339+05:30","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-03-17T22:51:37.9809211+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/6znlqhpb/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:52:01.36101+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/6znlqhpb/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:52:26.4345294+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/6znlqhpb/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:53:15.879473+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/6znlqhpb/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:53:39.437468+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/6znlqhpb/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:53:54.9908286+05:30","level":"INFO","msg":"Stopping system monitor"}
{"time":"2025-03-17T22:53:54.9913362+05:30","level":"INFO","msg":"Stopped system monitor"}
{"time":"2025-03-17T22:53:55.9957208+05:30","level":"INFO","msg":"handler: operation stats","stats":{"operations":[{"desc":"uploading history steps 6-7, summary","runtime_seconds":37.5951155,"error_status":"retrying: Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/6znlqhpb/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."},{"desc":"uploading output.log","runtime_seconds":0.1165744},{"desc":"uploading wandb-summary.json","runtime_seconds":0.1165744,"progress":"270B/270B"}],"total_operations":3}}
{"time":"2025-03-17T22:53:57.269905+05:30","level":"INFO","msg":"fileTransfer: Close: file transfer manager closed"}
{"time":"2025-03-17T22:54:02.9748213+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/6znlqhpb/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:54:29.1076546+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/6znlqhpb/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:54:31.5244959+05:30","level":"INFO","msg":"stream: closing","id":"6znlqhpb"}
{"time":"2025-03-17T22:54:31.5244959+05:30","level":"INFO","msg":"handler: closed","stream_id":"6znlqhpb"}
{"time":"2025-03-17T22:54:31.5244959+05:30","level":"INFO","msg":"sender: closed","stream_id":"6znlqhpb"}
{"time":"2025-03-17T22:54:31.5244959+05:30","level":"INFO","msg":"writer: Close: closed","stream_id":"6znlqhpb"}
{"time":"2025-03-17T22:54:31.525002+05:30","level":"INFO","msg":"stream: closed","id":"6znlqhpb"}
