{"time":"2025-03-17T22:25:28.9734326+05:30","level":"INFO","msg":"stream: starting","core version":"0.19.8","symlink path":"C:\\Users\\praha\\Documents\\IIT madras\\Acads\\sem 10\\introtoDL\\DA6401_A01\\wandb\\run-20250317_222528-dub0oxkz\\logs\\debug-core.log"}
{"time":"2025-03-17T22:25:29.0895173+05:30","level":"INFO","msg":"created new stream","id":"dub0oxkz"}
{"time":"2025-03-17T22:25:29.0895173+05:30","level":"INFO","msg":"stream: started","id":"dub0oxkz"}
{"time":"2025-03-17T22:25:29.0895173+05:30","level":"INFO","msg":"writer: Do: started","stream_id":"dub0oxkz"}
{"time":"2025-03-17T22:25:29.0895173+05:30","level":"INFO","msg":"handler: started","stream_id":"dub0oxkz"}
{"time":"2025-03-17T22:25:29.0895173+05:30","level":"INFO","msg":"sender: started","stream_id":"dub0oxkz"}
{"time":"2025-03-17T22:25:50.1549193+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:25:52.9597098+05:30","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-03-17T22:25:54.0463228+05:30","level":"INFO","msg":"Stopping system monitor"}
{"time":"2025-03-17T22:25:54.0481652+05:30","level":"INFO","msg":"Stopped system monitor"}
{"time":"2025-03-17T22:25:55.0690765+05:30","level":"INFO","msg":"handler: operation stats","stats":{"operations":[{"desc":"uploading data","runtime_seconds":1.3144677},{"desc":"uploading requirements.txt","runtime_seconds":1.1727595,"progress":"3.6KB/3.6KB"},{"desc":"uploading output.log","runtime_seconds":0.4787934,"progress":"419B/419B"},{"desc":"uploading wandb-summary.json","runtime_seconds":0.4787934,"progress":"25B/25B"},{"desc":"uploading config.yaml","runtime_seconds":0.0465073,"progress":"921B/921B"}],"total_operations":5}}
{"time":"2025-03-17T22:25:55.9041927+05:30","level":"INFO","msg":"fileTransfer: Close: file transfer manager closed"}
{"time":"2025-03-17T22:26:14.7826399+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/dub0oxkz/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
