{"time":"2025-03-17T22:17:59.9040232+05:30","level":"INFO","msg":"stream: starting","core version":"0.19.8","symlink path":"C:\\Users\\praha\\Documents\\IIT madras\\Acads\\sem 10\\introtoDL\\DA6401_A01\\wandb\\run-20250317_221759-zu5zjlts\\logs\\debug-core.log"}
{"time":"2025-03-17T22:18:00.0235623+05:30","level":"INFO","msg":"created new stream","id":"zu5zjlts"}
{"time":"2025-03-17T22:18:00.0235623+05:30","level":"INFO","msg":"stream: started","id":"zu5zjlts"}
{"time":"2025-03-17T22:18:00.0235623+05:30","level":"INFO","msg":"writer: Do: started","stream_id":"zu5zjlts"}
{"time":"2025-03-17T22:18:00.0235623+05:30","level":"INFO","msg":"sender: started","stream_id":"zu5zjlts"}
{"time":"2025-03-17T22:18:00.024096+05:30","level":"INFO","msg":"handler: started","stream_id":"zu5zjlts"}
{"time":"2025-03-17T22:18:21.0802399+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:18:23.8714225+05:30","level":"ERROR","msg":"HTTP error","status":403,"method":"POST","url":"https://api.wandb.ai/graphql"}
{"time":"2025-03-17T22:18:23.8714225+05:30","level":"ERROR","msg":"sender: upsertRun:","error":"failed to upsert bucket: returned error 403: {\"data\":{\"upsertBucket\":null},\"errors\":[{\"message\":\"permission denied\",\"path\":[\"upsertBucket\"],\"extensions\":{\"code\":\"PERMISSION_ERROR\"}}]}"}
