{"time":"2025-03-17T23:01:02.8617437+05:30","level":"INFO","msg":"stream: starting","core version":"0.19.8","symlink path":"C:\\Users\\praha\\Documents\\IIT madras\\Acads\\sem 10\\introtoDL\\DA6401_A01\\wandb\\run-20250317_230102-agdhfb1h\\logs\\debug-core.log"}
{"time":"2025-03-17T23:01:02.9774925+05:30","level":"INFO","msg":"created new stream","id":"agdhfb1h"}
{"time":"2025-03-17T23:01:02.9774925+05:30","level":"INFO","msg":"stream: started","id":"agdhfb1h"}
{"time":"2025-03-17T23:01:02.9774925+05:30","level":"INFO","msg":"writer: Do: started","stream_id":"agdhfb1h"}
{"time":"2025-03-17T23:01:02.9774925+05:30","level":"INFO","msg":"handler: started","stream_id":"agdhfb1h"}
{"time":"2025-03-17T23:01:02.9774925+05:30","level":"INFO","msg":"sender: started","stream_id":"agdhfb1h"}
{"time":"2025-03-17T23:01:03.351217+05:30","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-03-17T23:01:25.2024063+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/agdhfb1h/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T23:01:30.3246177+05:30","level":"INFO","msg":"Stopping system monitor"}
{"time":"2025-03-17T23:01:30.3251233+05:30","level":"INFO","msg":"Stopped system monitor"}
{"time":"2025-03-17T23:01:31.3379096+05:30","level":"INFO","msg":"handler: operation stats","stats":{"operations":[{"desc":"uploading history steps 0-8, summary","runtime_seconds":3.7204513},{"desc":"uploading config.yaml","runtime_seconds":0.0877307,"progress":"998B/998B"}],"total_operations":2}}
{"time":"2025-03-17T23:01:32.2557442+05:30","level":"INFO","msg":"fileTransfer: Close: file transfer manager closed"}
{"time":"2025-03-17T23:01:48.6624638+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/agdhfb1h/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T23:02:12.0587689+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/agdhfb1h/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T23:02:31.6241962+05:30","level":"INFO","msg":"handler: operation stats","stats":{"operations":[{"desc":"uploading history steps 0-8, summary","runtime_seconds":64.0067379,"error_status":"retrying: Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/agdhfb1h/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}],"total_operations":1}}
{"time":"2025-03-17T23:02:37.8855713+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/agdhfb1h/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T23:03:08.8834003+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/agdhfb1h/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T23:03:31.7800499+05:30","level":"INFO","msg":"handler: operation stats","stats":{"operations":[{"desc":"uploading history steps 9-9, summary","runtime_seconds":43.9279835,"error_status":"retrying: Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/agdhfb1h/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}],"total_operations":1}}
{"time":"2025-03-17T23:03:32.4296251+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/agdhfb1h/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T23:03:37.3234386+05:30","level":"INFO","msg":"stream: closing","id":"agdhfb1h"}
{"time":"2025-03-17T23:03:37.3234386+05:30","level":"INFO","msg":"handler: closed","stream_id":"agdhfb1h"}
{"time":"2025-03-17T23:03:37.3234386+05:30","level":"INFO","msg":"writer: Close: closed","stream_id":"agdhfb1h"}
{"time":"2025-03-17T23:03:37.3234386+05:30","level":"INFO","msg":"sender: closed","stream_id":"agdhfb1h"}
{"time":"2025-03-17T23:03:37.3240313+05:30","level":"INFO","msg":"stream: closed","id":"agdhfb1h"}
