{"time":"2025-03-17T22:58:24.8789546+05:30","level":"INFO","msg":"stream: starting","core version":"0.19.8","symlink path":"C:\\Users\\praha\\Documents\\IIT madras\\Acads\\sem 10\\introtoDL\\DA6401_A01\\wandb\\run-20250317_225824-h5ccle69\\logs\\debug-core.log"}
{"time":"2025-03-17T22:58:24.9970019+05:30","level":"INFO","msg":"created new stream","id":"h5ccle69"}
{"time":"2025-03-17T22:58:24.9970019+05:30","level":"INFO","msg":"stream: started","id":"h5ccle69"}
{"time":"2025-03-17T22:58:24.9970019+05:30","level":"INFO","msg":"sender: started","stream_id":"h5ccle69"}
{"time":"2025-03-17T22:58:24.9970019+05:30","level":"INFO","msg":"writer: Do: started","stream_id":"h5ccle69"}
{"time":"2025-03-17T22:58:24.9975321+05:30","level":"INFO","msg":"handler: started","stream_id":"h5ccle69"}
{"time":"2025-03-17T22:58:46.0572998+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:59:09.3432326+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:59:13.9726689+05:30","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-03-17T22:59:35.0036579+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/h5ccle69/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:59:37.5655244+05:30","level":"INFO","msg":"Stopping system monitor"}
{"time":"2025-03-17T22:59:37.5660097+05:30","level":"INFO","msg":"Stopped system monitor"}
{"time":"2025-03-17T22:59:38.5816339+05:30","level":"INFO","msg":"handler: operation stats","stats":{"operations":[{"desc":"uploading history steps 0-4, summary","runtime_seconds":0.7851647},{"desc":"uploading output.log","runtime_seconds":0.4340621},{"desc":"uploading config.yaml","runtime_seconds":0.133988,"progress":"997B/997B"}],"total_operations":3}}
{"time":"2025-03-17T22:59:38.7904733+05:30","level":"INFO","msg":"fileTransfer: Close: file transfer manager closed"}
{"time":"2025-03-17T22:59:58.8585384+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/h5ccle69/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T23:00:22.4690901+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/h5ccle69/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T23:00:38.6684798+05:30","level":"INFO","msg":"handler: operation stats","stats":{"operations":[{"desc":"uploading summary","runtime_seconds":37.2499005,"error_status":"retrying: Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/h5ccle69/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}],"total_operations":1}}
{"time":"2025-03-17T23:00:45.920991+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/h5ccle69/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T23:00:50.4523983+05:30","level":"INFO","msg":"stream: closing","id":"h5ccle69"}
{"time":"2025-03-17T23:00:50.4523983+05:30","level":"INFO","msg":"handler: closed","stream_id":"h5ccle69"}
{"time":"2025-03-17T23:00:50.4523983+05:30","level":"INFO","msg":"writer: Close: closed","stream_id":"h5ccle69"}
{"time":"2025-03-17T23:00:50.4523983+05:30","level":"INFO","msg":"sender: closed","stream_id":"h5ccle69"}
{"time":"2025-03-17T23:00:50.4529089+05:30","level":"INFO","msg":"stream: closed","id":"h5ccle69"}
