{"time":"2025-03-17T22:54:37.0624002+05:30","level":"INFO","msg":"stream: starting","core version":"0.19.8","symlink path":"C:\\Users\\praha\\Documents\\IIT madras\\Acads\\sem 10\\introtoDL\\DA6401_A01\\wandb\\run-20250317_225437-uq6x7oxc\\logs\\debug-core.log"}
{"time":"2025-03-17T22:54:37.18007+05:30","level":"INFO","msg":"created new stream","id":"uq6x7oxc"}
{"time":"2025-03-17T22:54:37.1804376+05:30","level":"INFO","msg":"stream: started","id":"uq6x7oxc"}
{"time":"2025-03-17T22:54:37.1805953+05:30","level":"INFO","msg":"handler: started","stream_id":"uq6x7oxc"}
{"time":"2025-03-17T22:54:37.1805953+05:30","level":"INFO","msg":"sender: started","stream_id":"uq6x7oxc"}
{"time":"2025-03-17T22:54:37.1805953+05:30","level":"INFO","msg":"writer: Do: started","stream_id":"uq6x7oxc"}
{"time":"2025-03-17T22:54:37.5885947+05:30","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-03-17T22:54:59.4296509+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/uq6x7oxc/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:55:08.9269285+05:30","level":"INFO","msg":"Stopping system monitor"}
{"time":"2025-03-17T22:55:08.9274636+05:30","level":"INFO","msg":"Stopped system monitor"}
{"time":"2025-03-17T22:55:09.9485347+05:30","level":"INFO","msg":"handler: operation stats","stats":{"operations":[{"desc":"uploading history steps 0-6, summary","runtime_seconds":7.7827817},{"desc":"uploading output.log","runtime_seconds":0.1553984},{"desc":"uploading wandb-summary.json","runtime_seconds":0.1553984,"progress":"298B/298B"}],"total_operations":3}}
{"time":"2025-03-17T22:55:10.4741948+05:30","level":"INFO","msg":"fileTransfer: Close: file transfer manager closed"}
{"time":"2025-03-17T22:55:23.221123+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/uq6x7oxc/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:55:46.8649647+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/uq6x7oxc/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:56:10.0612731+05:30","level":"INFO","msg":"handler: operation stats","stats":{"operations":[{"desc":"uploading history steps 7-9, summary","runtime_seconds":44.2428442,"error_status":"retrying: Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/uq6x7oxc/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}],"total_operations":1}}
{"time":"2025-03-17T22:56:10.2299146+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/uq6x7oxc/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:56:36.1740241+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/uq6x7oxc/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:56:46.1267743+05:30","level":"INFO","msg":"stream: closing","id":"uq6x7oxc"}
{"time":"2025-03-17T22:56:46.1267743+05:30","level":"INFO","msg":"handler: closed","stream_id":"uq6x7oxc"}
{"time":"2025-03-17T22:56:46.1267743+05:30","level":"INFO","msg":"writer: Close: closed","stream_id":"uq6x7oxc"}
{"time":"2025-03-17T22:56:46.1267743+05:30","level":"INFO","msg":"sender: closed","stream_id":"uq6x7oxc"}
{"time":"2025-03-17T22:56:46.1272888+05:30","level":"INFO","msg":"stream: closed","id":"uq6x7oxc"}
