{"time":"2025-03-17T23:08:44.7970761+05:30","level":"INFO","msg":"stream: starting","core version":"0.19.8","symlink path":"C:\\Users\\praha\\Documents\\IIT madras\\Acads\\sem 10\\introtoDL\\DA6401_A01\\wandb\\run-20250317_230844-hbieb33a\\logs\\debug-core.log"}
{"time":"2025-03-17T23:08:44.9133418+05:30","level":"INFO","msg":"created new stream","id":"hbieb33a"}
{"time":"2025-03-17T23:08:44.9133418+05:30","level":"INFO","msg":"stream: started","id":"hbieb33a"}
{"time":"2025-03-17T23:08:44.9133418+05:30","level":"INFO","msg":"handler: started","stream_id":"hbieb33a"}
{"time":"2025-03-17T23:08:44.9133418+05:30","level":"INFO","msg":"sender: started","stream_id":"hbieb33a"}
{"time":"2025-03-17T23:08:44.9133418+05:30","level":"INFO","msg":"writer: Do: started","stream_id":"hbieb33a"}
{"time":"2025-03-17T23:08:45.3181704+05:30","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-03-17T23:09:07.1100359+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/hbieb33a/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T23:09:15.9832371+05:30","level":"INFO","msg":"Stopping system monitor"}
{"time":"2025-03-17T23:09:15.9832371+05:30","level":"INFO","msg":"Stopped system monitor"}
{"time":"2025-03-17T23:09:17.0024892+05:30","level":"INFO","msg":"handler: operation stats","stats":{"operations":[{"desc":"uploading data","runtime_seconds":30.9341293,"error_status":"retrying: Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/hbieb33a/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."},{"desc":"uploading output.log","runtime_seconds":0.4397993},{"desc":"uploading wandb-summary.json","runtime_seconds":0.4397993,"progress":"299B/299B"},{"desc":"uploading config.yaml","runtime_seconds":0.1420529,"progress":"999B/999B"}],"total_operations":4}}
{"time":"2025-03-17T23:09:17.9013946+05:30","level":"INFO","msg":"fileTransfer: Close: file transfer manager closed"}
{"time":"2025-03-17T23:09:30.4207688+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/hbieb33a/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T23:09:55.664817+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/hbieb33a/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T23:10:17.2826897+05:30","level":"INFO","msg":"handler: operation stats","stats":{"operations":[{"desc":"uploading data","runtime_seconds":91.2143298,"error_status":"retrying: Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/hbieb33a/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}],"total_operations":1}}
{"time":"2025-03-17T23:10:25.5434884+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/hbieb33a/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T23:11:05.0683284+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/prahaladvathsan-iit-madras/DA640_A01/hbieb33a/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T23:11:08.0435252+05:30","level":"INFO","msg":"stream: closing","id":"hbieb33a"}
{"time":"2025-03-17T23:11:08.0435252+05:30","level":"INFO","msg":"handler: closed","stream_id":"hbieb33a"}
{"time":"2025-03-17T23:11:08.0440445+05:30","level":"INFO","msg":"writer: Close: closed","stream_id":"hbieb33a"}
{"time":"2025-03-17T23:11:08.0445773+05:30","level":"INFO","msg":"sender: closed","stream_id":"hbieb33a"}
{"time":"2025-03-17T23:11:08.0445773+05:30","level":"INFO","msg":"stream: closed","id":"hbieb33a"}
